name: rnaseq-pipeline
channels:
- conda-forge
- bioconda
dependencies:
- python=3
- pip
- cutadapt
- pandas
- luigi==2.8.13
- multiqc==1.9
- sra-tools
- fastqc
- star==2.7.3a
- entrez-direct
- gunicorn
